apiVersion: v1
kind: Template
metadata:
 labels:
   name: "${SERVICE_NAME}"
 annotations:
   openshift.io/display-name: "Openshift Template"
   openshift.alpha.openshift.io/wait-for-ready: "true"
objects:
apiVersion: v1
kind: Imagestream
metadata:
  labels:
    name: "${SERVICE_NAME}"
  annotaions:
    openshift.io/display-name: "Maven Image Stream"
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: "${SERVICE_NAME}"
  annotaions:
    openshift.io/diplay-name: "Maven Build Config"
    openshift.alpha.openshift.io/wait-for-ready: "true"
spec:
  resources:
    limits:
      cpu: 2000m
      memory: 2000Mi
    requests:
      cpu: 200m
      memory: 512Mi
  source:
    git:
      uri: "${SOURCE_REPOSITORY_URL}"
      ref: "${SOURCE_REPOSITORY_REF}"
    sourceSecret:
       name:
  strategy:
    dockerstrategy:
      dockerfilePath: "openshift/dockerfile/${SERVICE_NAME}/${SERVICE_NAME}.docker"
  output:
    to:
      kind: "ImageStreamTag"
      name: "${SERVICE_NAME}:${VERSION}"
  triggers:
  - type: "ConfigChange"
  - type: "ImageChange"
   imageChangeParams:
     automatic: true
parameters:
- name: "NAMESPACE"
  displayName: "Namespace"
  required: true
  description: "The OpenShift Namespace where the ImageStream resides."
  value: "openshift"
- name: "SERVICE_NAME"
  displayName: "Service name"
  required: true
  description: "The OpenShift service name."
  value: "maven"
- name: "REGISTRY_URL"
  displayName: "Docker registry URL"
  required: true
  description: "The OpenShift docker registry URL from which to pull images for deployments."
  value: " "
- name: "SOURCE_REPOSITORY_URL"
  displayName: "Git Repository URL"
  description: "The URL of the repository with the OpenShift templates."
  value: "git@github.com:Kwenene/Openshift.git"
- name: "SOURCE_REPOSITORY_REF"
  displayName: "Git Reference"
  description: "Set this to a branch name, tag or other ref of your repository if you are not using the default branch."
  value: "dev"
- name: "VERSION"
  displayName: "Maven version"
  required: true
  description: "The version of Maven."
  value: "3.5.4"

